name: 'Laravel Test'
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer
