name: 'Laravel Test'
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        id: get-composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_ENV

      - name: Cache Composer dependencies
        id: cache-composer
        uses: actions/cache@v3
        with:
          path: |
            vendor
            ${{ env.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Check cache contents
        run: ls -la vendor || echo "vendor is empty" && ls -la ${{ env.dir }} || echo "dir is empty"

      - name: Install Composer dependencies
        if: steps.cache-composer.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Start Test
        run: php artisan test

      - name: Install zip
        run: sudo apt-get install -y zip
  
      - name: Zip files excluding storage folder
        run: zip -r deploy.zip . -x "storage/*" -x ".git/*" -x ".env"

      - name: Create Deploy directory
        run: mkdir -p deploy && mv deploy.zip deploy/deploy.zip

      - name: Check Deploy files
        run: ls - al deplay

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'deploy'

      # - uses: shallwefootball/s3-upload-action@master
      #   name: Upload S3
      #   id: S3
      #   with:
      #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
      #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      #     aws_bucket: ${{ secrets.AWS_BUCKET }}
      #     source_dir: 'static'
